apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  OPENAI_API_KEY: "{{ .Values.env.llm.openai.api_key }}"
  GEMINI_API_KEY: "{{ .Values.env.llm.gemini.api_key }}"
  XAI_API_KEY: "{{ .Values.env.llm.xai.api_key }}"
  
  SUPABASE_URL: "{{ .Values.env.supabase.url }}"
  SUPABASE_KEY: "{{ .Values.env.supabase.key }}"
  
  LANGCHAIN_API_KEY: "{{ .Values.env.langsmith.api_key }}"
  HF_TOKEN: "{{ .Values.env.huggingface.token }}"
  
  NAVER_CLIENT_ID: "{{ .Values.env.naver.client_id }}"
  NAVER_CLIENT_SECRET: "{{ .Values.env.naver.client_secret }}"
